llm:
  # gpt-3.5-turbo or gpt-4
  model: "gpt-3.5-turbo-16k"
  azure_openai_endpoint:
  openai_org_id:
nlp:
  server_url: "http://localhost:8080"
memory:
  message_window: 48
extractors:
  summarizer:
    enabled: true
  entities:
    enabled: true
  intent:
    enabled: true
  embeddings:
    enabled: true
    dimensions: 1536
    model: "AdaEmbeddingV2"
#    dimensions: 768
#    model: "local"
memory_store:
  type: "postgres"
  postgres:
    dsn: "postgres://postgres:postgres@localhost:5432/?sslmode=disable"
server:
  port: 8000
auth:
  # Set to true to enable authentication
  required: false
  # Do not use this secret in production. The ZEP_AUTH_SECRET environment variable should be
  # set to a cryptographically secure secret. See the Zep docs for details.
  secret: "do-not-use-this-secret-in-production"
data:
  #  PurgeEvery is the period between hard deletes, in minutes.
  #  If set to 0 or undefined, hard deletes will not be performed.
  purge_every: 60
log:
  level: "info"
