services:
  # A Docker web service
  - type: web
    name: zep
    autoDeploy: false
    env: image
    plan: free
    image:
      url: ghcr.io/getzep/zep-cloud:0.8.1
    healthCheckPath: /healthz
    envVars:
      - key: PORT
        value: 8000
      - key: ZEP_MEMORY_STORE_POSTGRES_DSN
        fromDatabase:
          name: zep-postgres
          property: connectionString
      - key: ZEP_NLP_SERVER_HOSTPORT
        fromService:
          name: zep-nlp
          type: pserv
          property: hostport
      - key: ZEP_OPENAI_API_KEY
        sync: false
  - type: pserv
    name: zep-nlp
    autoDeploy: false
    env: image
    image:
      url: ghcr.io/getzep/zep-nlp-server:latest

databases:
  - name: zep-postgres
    databaseName: zep
    postgresMajorVersion: 15
    ipAllowList: [] # only allow internal connections
    plan: free
